name: HealthBar
main: cc.vastsea.healthbar.HealthBarPlugin
version: 1.3
description: A Spigot plugin to display the health of attacked entities using a boss bar
author: Snowball_233, zrll_
api-version: 1.16.4
